name: Build OpenSSL 3.1.2 (commit to repo)

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: centos:8  # lub rockylinux:9, almalinux:9, itp.

    steps:
      - name: Install build dependencies
        run: |
          yum -y install gcc make perl wget tar

      - name: Download and build OpenSSL
        run: |
          wget https://www.openssl.org/source/openssl-3.1.2.tar.gz
          tar -xzf openssl-3.1.2.tar.gz
          cd openssl-3.1.2
          ./Configure linux-x86_64 --prefix=/tmp/openssl-out
          make -j$(nproc)
          make install
          tar -czf /tmp/openssl-3.1.2-x86_64.tar.gz -C /tmp/openssl-out .


      - name: Upload archive
        uses: ./.github/actions/upload-artifact
        with:
          name: openssl-3.1.2-x86_64
          path: openssl-3.1.2-x86_64.tar.gz



