name: Build OpenSSL 3.1.2 (self-hosted)

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          if ! command -v make &> /dev/null; then echo "❌ make not found"; exit 1; fi
          if ! command -v gcc &> /dev/null; then echo "❌ gcc not found"; exit 1; fi
          if ! command -v perl &> /dev/null; then echo "❌ perl not found"; exit 1; fi

      - name: Download and build OpenSSL
        run: |
          wget https://www.openssl.org/source/openssl-3.1.2.tar.gz
          tar -xzf openssl-3.1.2.tar.gz
          cd openssl-3.1.2
          ./Configure linux-x86_64 --prefix=$PWD/openssl-install
          make -j$(nproc)
          make install

      - name: Copy tar.gz to repo
        run: |
          tar -czf openssl-3.1.2-x86_64.tar.gz -C openssl-install .
          cp openssl-3.1.2-x86_64.tar.gz $GITHUB_WORKSPACE/
