name: Build OpenSSL 3.1.2 (commit to repo)

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install build dependencies
        run: sudo apt update && sudo apt install -y build-essential perl wget

      - name: Download and build OpenSSL
        run: |
          wget https://www.openssl.org/source/openssl-3.1.2.tar.gz
          tar -xzf openssl-3.1.2.tar.gz
          mkdir openssl-output
          cd openssl-3.1.2
          ./Configure linux-x86_64 --prefix=$GITHUB_WORKSPACE/openssl-output
          make -j$(nproc)
          make install

      - name: Archive built OpenSSL
        run: |
          tar -czf openssl-3.1.2-x86_64.tar.gz -C openssl-output .

      - name: Commit built archive to repo
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add openssl-3.1.2-x86_64.tar.gz
          git commit -m "Add OpenSSL 3.1.2 archive"
          git push https://x-access-token:${{ secrets.token }}@github.com/${{ github.repository }} HEAD:main
        env:
          token: ${{ secrets.token }}

